# Generated by Django 4.2.5 on 2023-09-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userName',
            new_name='username',
        ),
    ]
